name: discovery
description: A minimal Flutter project.
dependencies:
  flutter:
    path: ../../../../../../flutter/packages/flutter
  v23discovery: ">=0.0.12 <0.1.0"
  uuid: any
dev_dependencies:
  flutter_tools:
    path: "../../../../../flutter/packages/flutter_tools"
